name: "Test compiling Swift Modelgen output"

on:
  push:
    branches:
      - test-swift-e2e

jobs:
  Build-Swift-Modelgen:
    name: Analyze
    runs-on: macos-13-xl
    permissions:
      actions: read
      contents: read

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Xcode Select
        run: xcode-select --version

      - name: Build and test
        run: xcodebuild -version

      - name: Check swift version
        run: swift --version
        
      - name: Enable SSH session
        uses: lhotari/action-upterm@v1
        
      - name: Check swift version again
        run: swift --version
        
