name: 'Test compiling Swift Modelgen output'

on: workflow_dispatch

env:
  MODELS_S3_URL: MYURL

jobs:
  Build-Swift-Modelgen:
    name: Analyze
    runs-on: macos-13-xl
    permissions:
      actions: read
      contents: read

    strategy:
      fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Xcode Select
        run: xcode-select --version

      - name: Build and test
        run: xcodebuild -version

      - name: Check swift version
        run: swift --version

      - name: Check current dir
        run: pwd

      - name: Build Swift Models
        run: ./scripts/test-swift-modelgen.sh
