name: 'Test compiling Swift Modelgen output'

on:
  workflow_dispatch:
    inputs:
      MODELS_S3_URL:
        description: 'S3 URL for models'
        required: true

jobs:
  Build-Swift-Modelgen:
    name: Analyze
    runs-on: macos-13-xl
    permissions:
      actions: read
      contents: read

    strategy:
      fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Xcode and Swift versions
        run: |
          xcodebuild -version
          swift --version

      - name: Build Swift Models
        env:
          MODELS_S3_URL: ${{ inputs.MODELS_S3_URL }}
        run: |
          echo "::add-mask::$MODELS_S3_URL" 
          ./scripts/test-swift-modelgen.sh
