name: "Test compiling Swift Modelgen output"

on:
  push:
    branches:
      - test-swift-e2e

jobs:
  Build-Swift-Modelgen:
    name: Analyze
    runs-on: macos-13-xl
    permissions:
      actions: read
      contents: read

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Xcode Select
        run: xcode-select --version

      - name: Build and test
        run: xcodebuild -version

      - name: Check swift version
        run: swift --version
      
      - name: Check current dir
        run: pwd
      
      - name: Create Swift app
        run: |
          mkdir swiftapp && cd swiftapp
          swift package init --type executable
          cat Package.swift
          rm -rf Package.swift
          echo '// swift-tools-version: 5.7
          import PackageDescription
          let package = Package(name: "swiftapp", platforms: [.macOS(.v10_15)], dependencies: [.package(url: "https://github.com/aws-amplify/amplify-swift", from: "2.12.0")   ], targets: [ .executableTarget( name: "swiftapp",  dependencies: [ .product(name: "Amplify", package: "amplify-swift") ], path: "Sources")]
          )' >> Package.swift
          cat Package.swift
          swift package resolve
          swift build && swift run
        
      - name: Enable SSH session
        uses: lhotari/action-upterm@v1
        with:
           limit-access-to-actor: false
        
